version: '3'
services:
  app:
    working_dir: /app
    build: ./app
    ports:
      - '4000:3000'
    volumes:
    - ./app/:/app
    - /app/node_modules
  storybook:
    build: ./app/.storybook
    volumes:
        - ./app/:/app
    ports:
      - '5000:3001'
